#!/usr/bin/env python3
"""
vps-relay/generate.py

读 chain-registry.tsv → 生成 3 个产物：
  - mihomo-relay/config.yaml （含 N 个 vmess listener，每个 proxy 字段绑到对应原家宽节点）
  - nginx/relay.conf         （含 N 个 location，反代到对应 mihomo listener port）
  - vmess-bundle.txt         （base64 V2Ray URI list，写入 Sub-Store sub vps-chain-residential.content）

凭据从 .secrets.local/credentials.env（gitignored）读取，不进 git。
"""

import argparse
import base64
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VPS_RELAY = REPO_ROOT / "vps-relay"
TSV_PATH = VPS_RELAY / "chain-registry.tsv"
DEFAULT_OUT = VPS_RELAY / ".secrets.local" / "out"
SECRETS_FILE = VPS_RELAY / ".secrets.local" / "credentials.env"


def load_secrets():
    if not SECRETS_FILE.exists():
        sys.stderr.write(
            f"ERROR: secrets file not found: {SECRETS_FILE}\n"
            f"Expected keys: RELAY_VM_UUID, RELAY_WS_PATH, BACKEND_PATH, RELAY_PUBLIC_HOST\n"
        )
        sys.exit(1)
    secrets = {}
    for line in SECRETS_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        k, _, v = line.partition("=")
        secrets[k.strip()] = v.strip()
    if not secrets.get("RELAY_VM_UUID") and secrets.get("RELAY_VLESS_UUID"):
        # Backward compatibility for the first relay rollout, which used the wrong
        # variable name while already generating vmess listeners.
        secrets["RELAY_VM_UUID"] = secrets["RELAY_VLESS_UUID"]
    required = ["RELAY_VM_UUID", "RELAY_WS_PATH", "BACKEND_PATH", "RELAY_PUBLIC_HOST"]
    missing = [k for k in required if not secrets.get(k)]
    if missing:
        sys.stderr.write(f"ERROR: missing secret keys: {missing}\n")
        sys.exit(1)
    return secrets


def parse_registry():
    rows = []
    for lineno, line in enumerate(TSV_PATH.read_text(encoding="utf-8").splitlines(), 1):
        line = line.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        # TAB 分隔（不用 | 因为 cnqq 节点名含 |）
        parts = [p.strip() for p in line.split("\t")]
        if len(parts) != 4:
            sys.stderr.write(f"WARN line {lineno}: expected 4 TAB-separated fields, got {len(parts)}\n")
            continue
        idx, region, upstream, display = parts
        try:
            idx_int = int(idx)
        except ValueError:
            sys.stderr.write(f"WARN line {lineno}: idx must be integer: {idx!r}\n")
            continue
        rows.append(
            {
                "idx": f"{idx_int:02d}",
                "region": region,
                "upstream": upstream,
                "display": display,
                "port": 18442 + idx_int,
            }
        )
    return rows


def gen_mihomo_config(rows, secrets, out_path):
    uuid = secrets["RELAY_VM_UUID"]
    ws_base = secrets["RELAY_WS_PATH"].rstrip("/")
    backend = secrets["BACKEND_PATH"]

    # 从 chain-registry.tsv 派生 cnqq-residential provider filter regex
    # 只 fetch 链式 listener 实际需要的节点（精确 upstream name 匹配），不漏不污染
    # YAML 输出策略：filter 字符串里只 escape regex meta（不 escape Unicode），用 yaml single-quote 包围
    YAML_REGEX_META = r".^$*+?()[]{}|\\"
    def _escape_for_regex_in_yaml_singlequote(s):
        # regex meta escape with backslash
        out = []
        for ch in s:
            if ch in YAML_REGEX_META:
                out.append("\\" + ch)
            else:
                out.append(ch)
        return "".join(out)
    upstream_names = [r["upstream"] for r in rows]
    filter_regex = "|".join(_escape_for_regex_in_yaml_singlequote(n) for n in upstream_names)
    # YAML single-quote escaping: ' -> ''
    filter_regex_yaml = filter_regex.replace("'", "''")

    listener_blocks = []
    chain_outbound_groups = []
    for r in rows:
        # listener.proxy 字段不能直接引用 proxy-provider 内节点，要中转一层 group
        # 每条 chain 一个 select group，use cnqq-residential + 精确 name filter
        single_filter = "^" + _escape_for_regex_in_yaml_singlequote(r["upstream"]) + "$"
        # YAML single-quote escape: ' -> ''
        single_filter_yaml = single_filter.replace("'", "''")
        listener_blocks.append(
            f"""  - name: chain-{r['idx']}
    type: vmess
    port: {r['port']}
    listen: 0.0.0.0
    users:
      - username: relay
        uuid: {uuid}
        alterId: 0
    ws-path: {ws_base}-{r['idx']}
    proxy: chain-{r['idx']}-out
"""
        )
        chain_outbound_groups.append(
            f"""  - name: chain-{r['idx']}-out
    type: select
    use:
      - cnqq-residential
      - user-landing
    filter: '{single_filter_yaml}'
"""
        )

    config = f"""# Generated by vps-relay/generate.py — DO NOT EDIT MANUALLY
# Source: vps-relay/chain-registry.tsv ({len(rows)} chains)
# 改链式节点：编辑 chain-registry.tsv 后跑 scripts/deploy-relay.sh

mixed-port: 0
log-level: info
external-controller: 0.0.0.0:9090
allow-lan: false
ipv6: false

listeners:
{''.join(listener_blocks)}
proxy-providers:
  # filter regex 由 chain-registry.tsv 派生 — 精确拉这 {len(rows)} 个 upstream 节点，不多不少
  cnqq-residential:
    type: http
    url: "http://sub-store:3001{backend}/download/aggregated-residential?target=ClashMeta"
    interval: 30
    path: ./data/providers/cnqq-residential.yaml
    filter: '{filter_regex_yaml}'
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300

  user-landing:
    type: http
    url: "http://sub-store:3001{backend}/download/collection/user-landing-airports?target=ClashMeta"
    interval: 30
    path: ./data/providers/user-landing.yaml
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300

# 每条 chain 对应一个 select group（精确 filter 1 个 cnqq 节点），
# listener.proxy 字段引用该 group → mihomo schema 能 resolve outbound
proxy-groups:
{''.join(chain_outbound_groups)}
  # 兜底：仅作 schema 占位，listener.proxy 已绕过 rules
  - name: "🏡 家宽-自动"
    type: url-test
    use:
      - cnqq-residential
      - user-landing
    url: http://cp.cloudflare.com/generate_204
    interval: 300
    tolerance: 50
    lazy: false

rules:
  - DOMAIN,sub-store,DIRECT
  - DOMAIN-SUFFIX,sub-store,DIRECT
  - MATCH,🏡 家宽-自动
"""
    out_path.write_text(config, encoding="utf-8")


def gen_nginx_conf(rows, secrets, out_path):
    ws_base = secrets["RELAY_WS_PATH"].rstrip("/")
    blocks = []
    for r in rows:
        blocks.append(
            f"""location ^~ {ws_base}-{r['idx']} {{
    if ($http_upgrade != "websocket") {{ return 404; }}
    proxy_pass http://127.0.0.1:{r['port']};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_read_timeout 300s;
    access_log off;
}}"""
        )
    out_path.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")


def gen_vmess_bundle(rows, secrets, out_path):
    uuid = secrets["RELAY_VM_UUID"]
    ws_base = secrets["RELAY_WS_PATH"].rstrip("/")
    host = secrets["RELAY_PUBLIC_HOST"]

    links = []
    for r in rows:
        d = {
            "v": "2",
            "ps": f"\U0001F3E1 链式 {r['display']} 家宽",  # 🏡 链式 ... 家宽
            "add": host,
            "port": "443",
            "id": uuid,
            "aid": "0",
            "scy": "auto",
            "net": "ws",
            "type": "none",
            "host": host,
            "path": f"{ws_base}-{r['idx']}",
            "tls": "tls",
            "sni": host,
        }
        link = "vmess://" + base64.b64encode(
            json.dumps(d, ensure_ascii=False).encode("utf-8")
        ).decode("ascii")
        links.append(link)
    raw = "\n".join(links)
    bundle_b64 = base64.b64encode(raw.encode("utf-8")).decode("ascii")
    out_path.write_text(bundle_b64, encoding="ascii")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT))
    args = parser.parse_args()

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)

    rows = parse_registry()
    if not rows:
        sys.stderr.write("ERROR: chain-registry.tsv has no valid rows\n")
        sys.exit(1)

    secrets = load_secrets()

    gen_mihomo_config(rows, secrets, out / "config.yaml")
    gen_nginx_conf(rows, secrets, out / "relay.conf")
    gen_vmess_bundle(rows, secrets, out / "vmess-bundle.txt")

    print(f"Generated {len(rows)} chains:")
    print(f"  -> {out / 'config.yaml'}")
    print(f"  -> {out / 'relay.conf'}")
    print(f"  -> {out / 'vmess-bundle.txt'}")
    print()
    print(f"Port range: 18443-{18442 + len(rows)}")
    print(f"WS path: {secrets['RELAY_WS_PATH'].rstrip('/')}-XX")


if __name__ == "__main__":
    main()
